import { Link } from 'react-router-dom'
import { ArrowUpRight, ArrowRight, Plus, BriefcaseBusiness, Users, CalendarDays, FileText, Clock3, ChevronRight } from 'lucide-react'
import { useAdminStore } from '../../features/admin/model/admin-store'
import { Badge, ExportButton } from '../../components/ui/AdminUi'
import { downloadCsv, shortDate } from '../../shared/lib/admin-utils'
import { useCurrentUser } from '../../features/auth/model/use-current-user'
import { useCases } from '../../features/cases/model/use-cases'

export function DashboardPage() {
  const { records, profile, activity } = useAdminStore()
  const { data: user } = useCurrentUser()
  const caseQuery = useCases('', 1)
  const caseTotal = caseQuery.data?.meta.total ?? 0
  const cases = caseQuery.data?.data ?? []
  const metrics = [
    { label: 'Expedientes propios', value: caseTotal, detail: 'Documentación bajo su cuenta', icon: BriefcaseBusiness, path: '/expedientes', bars: [35, 55, 45, 70, 62, 86, 100] },
    { label: 'Usuarios activos', value: records.usuarios.filter((item) => item.status === 'Activo').length, detail: 'Instructores, revisores y estudiantes', icon: Users, path: '/usuarios', bars: [25, 42, 36, 58, 76, 68, 88] },
    { label: 'Próximas audiencias', value: records.audiencias.filter((item) => item.status === 'Programada').length, detail: 'Sesiones programadas', icon: CalendarDays, path: '/audiencias', bars: [65, 35, 80, 55, 90, 65, 85] },
    { label: 'Documentos', value: records.documentos.length, detail: `${records.documentos.filter((item) => item.status === 'Por revisar').length} requieren validación`, icon: FileText, path: '/documentos', bars: [22, 38, 44, 63, 75, 84, 100] },
  ]
  return <>
    <div className="dashboard-heading"><div><p className="eyebrow">SU ESPACIO DE TRABAJO</p><h1>Buen día, {(user?.name ?? profile.name).split(' ')[0]}<span className="title-dot">.</span></h1><p className="page-description">Este es el estado de su espacio de formación jurídica.</p></div><div className="heading-actions"><ExportButton onClick={() => downloadCsv('resumen-jurissim.csv', [['Indicador', 'Total'], ...metrics.map((item) => [item.label, String(item.value)])])} /><Link className="btn btn-primary" to="/expedientes?crear=1"><Plus size={17} />Nuevo expediente</Link></div></div>
    <div className="period-line"><span><span className="live-dot" />Expedientes conectados a su cuenta</span><span>Otros indicadores: vista de demostración <span className="demo-tag">MUESTRA</span></span></div>
    <section className="metrics-grid" aria-label="Resumen institucional">{metrics.map(({ label, value, detail, icon: Icon, path, bars }) => <Link to={path} className="metric-card" key={label}><div className="metric-top"><Icon size={19} strokeWidth={1.7} /><span>{label}</span><ArrowUpRight size={16} /></div><div className="metric-value-row"><strong>{String(value).padStart(2, '0')}</strong><div className="mini-bars" aria-hidden="true">{bars.map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></div><p>{detail}</p></Link>)}</section>
    <div className="dashboard-grid"><section className="panel recent-cases"><div className="panel-heading"><div><p className="eyebrow">SEGUIMIENTO</p><h2>Expedientes recientes</h2></div><Link className="text-link" to="/expedientes">Ver todos <ArrowRight size={15} /></Link></div><div className="table-scroll"><table><thead><tr><th>EXPEDIENTE</th><th>ESTADO</th><th>ACTUALIZADO</th><th><span className="sr-only">Detalle</span></th></tr></thead><tbody>{caseQuery.isPending ? <tr><td colSpan={4}>Cargando sus expedientes…</td></tr> : caseQuery.isError ? <tr><td colSpan={4}>No pudimos cargar la lista. Abra expedientes para reintentar.</td></tr> : cases.slice(0, 4).map((item) => <tr key={item.id}><td><Link to={`/expedientes/${item.id}`} className="record-title">{item.title}</Link><small>{item.case_number || `EXP-${String(item.id).padStart(5, '0')}`} <span className="middle-dot">·</span> {item.file_count} documentos</small></td><td><Badge>{item.status === 'borrador' ? 'En preparación' : item.status === 'activo' ? 'Activo' : 'Archivado'}</Badge></td><td className="date-cell">{shortDate(item.updated_at ?? item.created_at)}</td><td><Link to={`/expedientes/${item.id}`} className="icon-button" aria-label={`Ver ${item.title}`}><ChevronRight size={17} /></Link></td></tr>)}</tbody></table></div><div className="panel-foot"><span><span className="live-dot" />{caseTotal} expedientes de su propiedad</span><Link to="/expedientes">Administrar expedientes <ArrowUpRight size={14} /></Link></div></section>
    <section className="agenda-panel"><div className="panel-heading"><div><p className="eyebrow">PLANIFICACIÓN</p><h2>Próximas audiencias</h2></div><CalendarDays size={19} /></div><div className="agenda-list">{records.audiencias.filter((item) => item.status === 'Programada').slice(0, 3).map((item) => <Link to="/audiencias" className="agenda-item" key={item.id}><div className="date-tile"><span>SEP</span><strong>{item.date.slice(-2)}</strong></div><div><p>{item.title}</p><small><Clock3 size={12} />{item.subtitle.split(' · ')[0]}<span>·</span>{item.owner.split(' ')[0]}</small></div></Link>)}</div><Link className="agenda-link" to="/audiencias">Administrar calendario <ArrowRight size={16} /></Link></section>
    <section className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">TRAZABILIDAD</p><h2>Actividad reciente</h2></div><Link className="text-link" to="/actividad">Ver registro <ArrowRight size={15} /></Link></div><div className="activity-list">{activity.slice(0, 4).map((item, index) => <div className="activity-row" key={index}><span className="activity-node"><FileText size={15} /></span><div><strong>{item.title}</strong><p>{item.detail}</p></div><time>{item.time}</time></div>)}</div></section>
    <section className="institution-panel"><span className="eyebrow">GESTIÓN DEL CONOCIMIENTO</span><div className="library-art" aria-hidden="true"><i /><i /><i /><i /><span>§</span></div><h2>Una base jurídica<br />bien documentada.</h2><p>Centralice normativa, jurisprudencia y material de consulta para cada práctica.</p><Link to="/biblioteca">Explorar biblioteca <ArrowUpRight size={17} /></Link></section></div>
  </>
}
