import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Plus, Pencil, Trash2, ChevronLeft, ChevronRight, FolderOpen, FileUp, ArrowUpRight } from 'lucide-react'
import { toast } from 'sonner'
import { useAdminStore } from '../../features/admin/model/admin-store'
import { sectionConfig, type AdminRecord, type Section } from '../../features/admin/model/demo-data'
import { Badge, PageHeading, SearchBox, Modal, Field, ExportButton } from '../../components/ui/AdminUi'
import { downloadCsv, shortDate } from '../../shared/lib/admin-utils'

export function RecordsPage({ section }: { section: Section }) {
  const config = sectionConfig[section]
  const [params, setParams] = useSearchParams()
  const { records, saveRecord, deleteRecord } = useAdminStore()
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState(params.get('estado') ?? '')
  const [category, setCategory] = useState('')
  const [page, setPage] = useState(1)
  const [editing, setEditing] = useState<AdminRecord | 'new' | null>(params.has('crear') ? 'new' : null)
  const [removing, setRemoving] = useState<AdminRecord | null>(null)
  const [viewing, setViewing] = useState<AdminRecord | null>(null)
  const [formError, setFormError] = useState('')
  const [fileName, setFileName] = useState('')
  const filtered = records[section].filter((item) => (!status || item.status === status) && (!category || item.category === category) && `${item.title} ${item.id} ${item.subtitle} ${item.owner}`.toLowerCase().includes(search.toLowerCase()))
  const pageCount = Math.max(1, Math.ceil(filtered.length / 6))
  const current = Math.min(page, pageCount)
  const shown = filtered.slice((current - 1) * 6, current * 6)
  const close = () => { setEditing(null); setFormError(''); setFileName(''); if (params.has('crear')) { params.delete('crear'); setParams(params, { replace: true }) } }
  const edit = typeof editing === 'object' && editing ? editing : undefined
  const save = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    const title = String(data.get('title') ?? '').trim()
    const subtitle = String(data.get('subtitle') ?? '').trim()
    if (!title) { setFormError('Escriba un nombre para el registro.'); return }
    if (section === 'usuarios' && records.usuarios.some((item) => item.id !== edit?.id && item.subtitle.toLowerCase() === subtitle.toLowerCase())) { setFormError('Este correo ya aparece en la demostración.'); return }
    const prefix = { expedientes: 'EXP', usuarios: 'USR', documentos: 'DOC', biblioteca: 'FUE', audiencias: 'AUD' }[section]
    saveRecord(section, { id: edit?.id ?? `${prefix}-${crypto.randomUUID().slice(0, 8).toUpperCase()}`, title, subtitle: fileName || subtitle, category: String(data.get('category')), status: String(data.get('status')), owner: String(data.get('owner')).trim(), date: String(data.get('date')), description: String(data.get('description')).trim() })
    close(); toast.success('Registro guardado en la demostración')
  }
  return <>
    <PageHeading eyebrow={config.eyebrow} title={config.title} description={config.description}><ExportButton onClick={() => downloadCsv(`${section}-demo.csv`, [['Referencia', 'Nombre', config.columns[1], 'Estado', config.columns[2], 'Fecha'], ...filtered.map((item) => [item.id, item.title, item.category, item.status, item.owner, item.date])])} /><button className="btn btn-primary" onClick={() => setEditing('new')}><Plus size={17} />{config.action}</button></PageHeading>
    <div className="collection-summary"><strong>{records[section].length}<span>registros en el espacio</span></strong><span className="collection-summary-note">Organización y control del archivo institucional</span></div>
    <section className="panel"><div className="collection-toolbar"><SearchBox value={search} onChange={(value) => { setSearch(value); setPage(1) }} /><div className="filter-group"><select aria-label="Filtrar por categoría" value={category} onChange={(e) => { setCategory(e.target.value); setPage(1) }}><option value="">Todas las categorías</option>{config.categories.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Filtrar por estado" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1) }}><option value="">Todos los estados</option>{config.statuses.map((value) => <option key={value}>{value}</option>)}</select></div></div>
      <div className="table-scroll"><table><thead><tr><th>{config.columns[0]}</th><th>{config.columns[1]}</th><th>Estado</th><th>{config.columns[2]}</th><th>{section === 'audiencias' ? 'Fecha de sesión' : 'Actualizado'}</th><th>Acciones</th></tr></thead><tbody>{shown.map((item) => <tr key={item.id}><td><div className="name-cell">{section === 'usuarios' && <span className="avatar table-avatar">{item.title.split(' ').slice(0, 2).map((word) => word[0]).join('')}</span>}<div>{section === 'expedientes' ? <Link className="record-title" to={`/expedientes/${item.id}`}>{item.title}</Link> : <button className="record-title" onClick={() => setViewing(item)}>{item.title}</button>}<small>{section === 'usuarios' || section === 'documentos' ? item.subtitle : item.id}</small></div></div></td><td>{item.category}</td><td><Badge>{item.status}</Badge></td><td>{item.owner}</td><td className="date-cell">{shortDate(item.date)}</td><td><div className="row-actions"><button className="icon-button" aria-label={`Editar ${item.title}`} onClick={() => { setEditing(item); setFormError('') }}><Pencil size={15} /></button><button className="icon-button danger" aria-label={`Eliminar ${item.title}`} onClick={() => setRemoving(item)}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div>
      {!shown.length && <div className="empty-state"><FolderOpen size={30} strokeWidth={1.3} /><h3>No hay registros para mostrar</h3><p>Pruebe otro término o quite los filtros seleccionados.</p><button className="text-link" onClick={() => { setSearch(''); setCategory(''); setStatus('') }}>Restablecer filtros</button></div>}
      <div className="pagination"><span>{filtered.length ? `${(current - 1) * 6 + 1}–${Math.min(current * 6, filtered.length)}` : '0'} de {filtered.length} registros</span><div><button aria-label="Página anterior" className="icon-button" disabled={current === 1} onClick={() => setPage(current - 1)}><ChevronLeft size={17} /></button><span>Página {current} de {pageCount}</span><button aria-label="Página siguiente" className="icon-button" disabled={current === pageCount} onClick={() => setPage(current + 1)}><ChevronRight size={17} /></button></div></div>
    </section><p className="page-note">Los registros pertenecen al entorno de demostración. Los cambios se conservan hasta recargar la página.</p>
    {editing && <Modal title={edit ? `Editar ${config.singular}` : config.action} description="Complete la información del registro de demostración." onClose={close}><form onSubmit={save} className="modal-body"><div className="form-grid"><Field label={section === 'usuarios' ? 'Nombre completo' : 'Título'}><input name="title" required maxLength={120} defaultValue={edit?.title} autoFocus /></Field><Field label={section === 'usuarios' ? 'Correo electrónico' : section === 'audiencias' ? 'Hora, duración y grupo' : 'Referencia o descripción breve'}><input name="subtitle" type={section === 'usuarios' ? 'email' : 'text'} required defaultValue={edit?.subtitle} placeholder={section === 'audiencias' ? '16:00 · 60 min · Grupo A' : ''} maxLength={160} /></Field><Field label={config.columns[1]}><select name="category" defaultValue={edit?.category ?? config.categories[0]}>{config.categories.map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Estado"><select name="status" defaultValue={edit?.status ?? config.statuses[0]}>{config.statuses.map((value) => <option key={value}>{value}</option>)}</select></Field><Field label={config.columns[2]}><input name="owner" required defaultValue={edit?.owner} maxLength={100} /></Field><Field label="Fecha"><input type="date" required name="date" defaultValue={edit?.date ?? '2026-09-15'} /></Field></div>{section === 'documentos' && <Field label="Archivo de muestra" hint="Solo se muestra el nombre. El contenido no se almacena ni se envía."><div className="upload-zone"><FileUp size={25} /><input type="file" aria-label="Seleccionar archivo de muestra" accept=".pdf,.docx,.png,.jpg,.jpeg,.txt" onChange={(e) => setFileName(e.target.files?.[0]?.name ?? '')} />{fileName && <small>{fileName}</small>}</div></Field>}<Field label="Observaciones"><textarea name="description" rows={3} defaultValue={edit?.description} maxLength={2000} placeholder="Información adicional para el equipo…" /></Field>{formError && <p role="alert" className="form-error">{formError}</p>}<div className="modal-actions"><button type="button" className="btn btn-secondary" onClick={close}>Cancelar</button><button className="btn btn-primary" type="submit">Guardar {config.singular}</button></div></form></Modal>}
    {removing && <Modal title={`Eliminar ${config.singular}`} onClose={() => setRemoving(null)}><div className="modal-body"><p>Se eliminará <strong>{removing.title}</strong> de los datos de demostración de esta sesión.</p><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setRemoving(null)}>Cancelar</button><button className="btn btn-danger" onClick={() => { deleteRecord(section, removing.id); setRemoving(null); toast.success('Registro eliminado de la demostración') }}>Eliminar registro</button></div></div></Modal>}
    {viewing && <Modal title={viewing.title} description={viewing.id} onClose={() => setViewing(null)}><div className="modal-body"><Badge>{viewing.status}</Badge><dl className="detail-list"><div><dt>{config.columns[1]}</dt><dd>{viewing.category}</dd></div><div><dt>{config.columns[2]}</dt><dd>{viewing.owner}</dd></div><div><dt>Referencia</dt><dd>{viewing.subtitle}</dd></div><div><dt>Fecha</dt><dd>{shortDate(viewing.date)}</dd></div></dl><p className="detail-description">{viewing.description || 'Registro de demostración para explorar la administración de la plataforma.'}</p>{section === 'documentos' && <p className="notice">Este registro no contiene un archivo descargable. La carga documental se conectará al backend posteriormente.</p>}<div className="modal-actions"><button className="btn btn-primary" onClick={() => { setEditing(viewing); setViewing(null) }}>Editar registro <ArrowUpRight size={16} /></button></div></div></Modal>}
  </>
}
